### ISSUE TITLE
multi choose error

### ISSUE THREAD

**Issue by amirhoseindgr** [shiv19/nativescript-cfalert-dialog#17]
hi guys . i get error when i choose more than 4 items in multiChoiceList 

error : multi select items and boolean array size not equal

 var cfalertDialog = new CFAlertDialog();
    var itemState = [false, false, false, false, false];
    var options = {
      dialogStyle: CFAlertStyle.ALERT,
      title: 'This is a simple list!',
      multiChoiceList: {
        items: ['first', 'second', 'third', 'fourth' ,'fifth'],
        selectedItems: itemState,
        onClick: function(dialogInterface, index, b) {
          console.log(dialogInterface);
          console.log(index);
          console.log(b);
        },
      },
      buttons: [
        {
          text: 'Okay',
          buttonStyle: CFAlertActionStyle.POSITIVE,
          buttonAlignment: CFAlertActionAlignment.END,
          onClick: function(response) {
            console.log(response);
          },
        },
      ],
    };
    cfalertDialog.show(options);

i use 1.0.6 version

**Comment by shiv19** [comment]
This issue was fixed in version 1.0.12
#15
