### ISSUE TITLE
.show() to return a Promise

### ISSUE THREAD

**Issue by stevenspiel** [shiv19/nativescript-cfalert-dialog#18]
Hey, fantastic plugin! Great work. It is very well written and a delight to use.

I have a feature request. What is the feasibility of the `show()` function returning a promise, rather than `void`? For example, if I wanted to show a few dialogs in sequence, but perform async tasks in between them. Maybe the `show()` function could return whatever is returned in the `onClick()` callback?

**Comment by shiv19** [comment]
Hi Steven,
Good idea. I'll consider this. Thank you :)

**Comment by stevenspiel** [comment]
Cool! If you point me in the right direction, I could fork it and submit a PR.

**Comment by shiv19** [comment]
a promise wouldn't work well for Android multiple choice list or even a single choice list.
cus currently, the callback is called everytime the user selects something on the list. A promise can resolve only once

**Comment by shiv19** [comment]
@stevenspiel Cheers! released as v1.0.13 😄

**Comment by stevenspiel** [comment]
whaaaaaat? that's amazing!!! awesome!

**Comment by shiv19** [comment]
`show(options): Promise<string>;`

Shows the CFAlert Dialog based on the options provided. It returns a promise which can either resolve with a button title (if button was clicked), or it can resolve empty (undefined).

**Comment by shiv19** [comment]
It won't work for multichoice, single choice and simple list.
(these are android only parts of the plugin)
