### ISSUE TITLE
Is linear-gradient supported?

### ISSUE THREAD

**Issue by JuanDeLeon** [shiv19/nativescript-cfalert-dialog#23]
Running on iOS simulator iPhone 8, NS 5.2

I tried to set the options.backgroundColor property on a BottomSheet dialog like this:
`dialogStyle: this.$CFAlertStyle.BOTTOM_SHEET,`
`backgroundColor: linear-gradient(to bottom, #304B99, #FFFFFF)`

But it didn't work. The dialog is not shown at all. 
No error logs or anything.

**Comment by shiv19** [comment]
@JuanDeLeon
Sorry Linear gradient background is not supported by this plugin
