### ISSUE TITLE
Can I render custom elements in the dialog?

### ISSUE THREAD

**Issue by martinsotirov** [shiv19/nativescript-cfalert-dialog#24]
Hi, I have a quick question – are the dialogs limited to the available form elements (buttons, radio buttons, checkboxes etc.) or can I freely render my own components? Like for example, I'd like to have a pill button, a linear slider etc.

**Comment by sissingclay** [comment]
Hi,

I can't get this to work.

```
@ViewChild('switch') stackRef: ElementRef;

    myNativeStack: StackLayout;

    constructor(private _page: Page) {}

    ngAfterViewInit(): void {
        this._page.getViewById(
            'switch'
        );
        this.myNativeStack = this.stackRef.nativeElement;

        const cfalertDialog = new CFAlertDialog();
        cfalertDialog
            .show({
                // Options go here
                dialogStyle:
                    CFAlertStyle.BOTTOM_SHEET,
                headerView: this
                    .myNativeStack
            })
            .then(_ =>
                console.log('test', _)
            )
            .catch(e =>
                console.log('e', e)
            );
    }
```
This is the error I keep getting.
`ERROR Error: Cannot convert object to Landroid/view/View; at index 0`

**Comment by shiv19** [comment]
The header and footer views only support native views. And not nativescript views.

**Comment by sissingclay** [comment]
@shiv19 could you give me an example of how to achieve this please? Is it possible to do in NativeScript?

**Comment by shiv19** [comment]
Please refer #7
