### ISSUE TITLE
Button textColor does not work correctly on Android

### ISSUE THREAD

**Issue by kfisto** [shiv19/nativescript-cfalert-dialog#25]
If you specify '#ffffff' for the button textColor property, the dialog will show, but the text color is not white. If you specify something other than '#ffffff', like '#ff0000', the dialog with not show and the following error will be thrown and show in the console:

ERROR Error: Uncaught (in promise): Error: android.content.res.Resources$NotFoundException: Resource ID #0xffff0000

This is easy to reproduce using the provided demo app.

**Comment by JWiseCoder** [comment]
+1

This is because this plugin is still using version 1.0.1 of CFAlertDialog.  If you go into the include.gradle file and change it to 1.1.0, textColor works fine.  This plugin needs to be updated to use version 1.1.0

**Comment by shiv19** [comment]
v1.0.15 has a fix for this. Thanks @JWiseCoder
