### ISSUE TITLE
Needs to go use version 1.1.0 of CFAlertDialog (or later)

### ISSUE THREAD

**Issue by JWiseCoder** [shiv19/nativescript-cfalert-dialog#26]
The main problem with this plugin being on version 1.0.1 of CFAlertDialog is that the textColor does not work as expected.  This has (apparently) been fixed in version 1.1.0.  I can change the include.gradle to use version 1.1.0 and it works fine.

Please update this plugin to use version 1.1.0 (or later) of CFAlertDialog.

**Comment by shiv19** [comment]
@JWiseCoder thank you for reporting this. I'll update version and release a new version of the plugin

**Comment by shiv19** [comment]
@JWiseCoder 
Released as v1.0.15 :)
