### ISSUE TITLE
textColor and backgroundColor of button is not set up for Android

### ISSUE THREAD

**Issue by HoangJK** [shiv19/nativescript-cfalert-dialog#3]
Please apply textColor and backgroundColor of button for Android.
`
if (options.buttons) {
      var _loop_1 = function (i) {
        var button = options.buttons[i]
        builder.addButton(button.text, -1, -1, actionStyles[button.buttonStyle], alignment[button.buttonAlignment], new android.content.DialogInterface.OnClickListener({
          onClick: function (dialog, which) {
            button.onClick(button.text)
            dialog.dismiss()
          }
        }))
      }
      for (var i = 0; i < options.buttons.length; i++) {
        _loop_1(i)
      }
    }
`

**Comment by edorozco** [comment]
Hey dude, 
I have the same problem, this code solved this issue ?

**Comment by tempurai** [comment]
I have same problem

**Comment by alexandruantonica** [comment]
I have the same problem.

**Comment by shiv19** [comment]
Problem solved and published as Plugin version 1.0.9 😄 
@HoangJK Thank you for reporting this. Sorry for the delay.
