### ISSUE TITLE
Plugin changes my app name

### ISSUE THREAD

**Issue by hrueger** [shiv19/nativescript-cfalert-dialog#31]
### Make sure to check the demo app(s) for sample usage 
I did.
### Make sure to check the existing issues in this repository 
I did.
### If the demo apps cannot help and there is no issue for your problem, tell us about it
The plugin changes my app name. On the home screen, everything is fine, but under Settings -> Apps my app is shown as `CFAlertDialog`. Also when I send a push message using nativescript-push-notifications, the app title is `CFAlertDialog`.

### Which platform(s) does your issue occur on?
- Android: yes, I don't know about IOS 
- Android 9
- Real device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.0.3
- Cross-platform modules: 6.0.7
- Runtime(s): android 6.0.2
- Plugin(s): 
```
"dependencies": {
        "@angular/animations": "^8.0.0",
        "@angular/cdk": "^8.1.1",
        "@angular/common": "8.0.0",
        "@angular/compiler": "8.0.0",
        "@angular/core": "8.0.0",
        "@angular/forms": "8.0.0",
        "@angular/http": "8.0.0-beta.10",
        "@angular/platform-browser": "8.0.0",
        "@angular/platform-browser-dynamic": "8.0.0",
        "@angular/router": "8.0.0",
        "@ctrl/ngx-emoji-mart": "^0.17.0",
        "@fortawesome/fontawesome-free": "^5.8.2",
        "@ng-bootstrap/ng-bootstrap": "^4.1.3",
        "@nstudio/nativescript-snackbar": "^1.0.0",
        "@syncfusion/ej2-angular-inputs": "^17.1.50",
        "@syncfusion/ej2-angular-layouts": "^17.2.36",
        "@syncfusion/ej2-angular-navigations": "^17.2.36",
        "@syncfusion/ej2-angular-popups": "^17.1.50",
        "@syncfusion/ej2-angular-schedule": "^17.1.51",
        "ajv": "^6.10.0",
        "angularx-flatpickr": "^6.1.0",
        "bootstrap": "^4.3.1",
        "chart.js": "^2.8.0",
        "chartjs-plugin-datalabels": "^0.6.0",
        "cldr-data": "^35.1.0",
        "core-js": "^2.6.5",
        "date-fns": "^1.30.1",
        "fontawesome": "^5.6.3",
        "nativescript-accordion": "^6.0.0-beta.2",
        "nativescript-angular": "8.0.2",
        "nativescript-cache": "^1.0.0",
        "nativescript-cfalert-dialog": "^1.0.15",
        "nativescript-clipboard": "^1.1.7",
        "nativescript-download-progress": "^1.2.0",
        "nativescript-emoji-picker": "^0.1.0",
        "nativescript-feedback": "^1.3.10",
        "nativescript-local-notifications": "^4.0.1",
        "nativescript-localstorage": "^2.0.1",
        "nativescript-modal-datetimepicker": "^1.2.0",
        "nativescript-multi-select": "^1.0.6",
        "nativescript-ngx-fonticon": "^4.2.0",
        "nativescript-pdf-view": "^2.0.1",
        "nativescript-photoviewer": "^2.1.5",
        "nativescript-plugin-firebase": "^9.1.0",
        "nativescript-progress-notifications": "^1.0.1",
        "nativescript-theme-core": "~1.0.6",
        "nativescript-ui-autocomplete": "5.0.0",
        "nativescript-ui-calendar": "5.0.0",
        "nativescript-ui-chart": "5.0.0",
        "nativescript-ui-dataform": "5.0.0",
        "nativescript-ui-gauge": "5.0.0",
        "nativescript-ui-listview": "7.0.2",
        "nativescript-ui-sidedrawer": "7.0.0",
        "nativescript-videoplayer": "^4.2.1",
        "ng2-charts": "^2.2.3",
        "ng2-pdfjs-viewer": "^4.0.5",
        "ngx-avatar": "^3.5.0",
        "ngx-contextmenu": "^5.2.0",
        "ngx-toastr": "^10.0.4",
        "reflect-metadata": "~0.1.13",
        "rxjs": "^6.5.2",
        "rxjs-compat": "^6.5.2",
        "tns-core-modules": "^6.0.1",
        "tns-platform-declarations": "^6.0.5",
        "zone.js": "0.9.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "0.13.4",
        "@angular/cli": "^7.3.9",
        "@angular/compiler-cli": "8.0.0",
        "@nativescript/schematics": "^0.5.2",
        "@types/jasmine": "~3.3.12",
        "@types/jasminewd2": "~2.0.6",
        "@types/node": "~12.0.2",
        "codelyzer": "~5.0.1",
        "jasmine-core": "~3.4.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.1.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.5",
        "karma-jasmine": "~2.0.1",
        "karma-jasmine-html-reporter": "^1.4.2",
        "nativescript-dev-webpack": "1.0.1",
        "node-sass": "4.12.0",
        "protractor": "~5.4.2",
        "systemjs-plugin-json": "^0.3.0",
        "ts-node": "~8.1.0",
        "tslint": "~5.16.0",
        "typescript": "3.4.5"
    },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
I just installed the plugin and included the module in my app.module.tns.ts and my app name was changed...

### Is there any code involved? 
I don't think so.

**Comment by shiv19** [comment]
Please use @nstudio/NativeScript-cfalert-dialog

**Comment by shiv19** [comment]
Thanks for reporting this. I'll add a deprecation warning to the readme and point to nstudio version of it

**Comment by hrueger** [comment]
Thanks.
I installed the plugin from here: https://www.npmjs.com/package/nativescript-cfalert-dialog
The github link also points to this repo...
Maybe you can fix that, too?
Or would it be possible to tell npm to install the nstudio version when just typing `npm i nativescript-cfalert-dialog`?

**Comment by shiv19** [comment]
Looks like there is no nStudio version of this plugin.
I'll use the package json provided and see if I can recreate the problem.

**Comment by hrueger** [comment]
Before I installed nativescript-cfalert-dialog, I had the same issue, but my app was called `TNSSideDrawer`...
Does that help you?
I'll unpack my apk and search for `CFAlertDialog` to find out where it is saved.

**Comment by shiv19** [comment]
Sounds more like an app configuration issue. How did you scaffold your app?

**Comment by hrueger** [comment]
I found the problem: Somehow the line `<string name="app_name">My App</string>` disappeared from `App_Resources/Android/src/main/res/values/strings.xml`. I don't know how this could happen.
I'm sorry that I thought this would be a bug of your plugin.

Should I create an issue in the nativescript repository that it takes a plugin name when the app name value in the `strings.xml` is not set?
Or do you think that this is a wanted behaviour?

**Comment by shiv19** [comment]
I wouldn't claim it as an issue in NativeScript. Everyone supplies the app name in strings.xml
