### ISSUE TITLE
bintray.com Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by ghost** [shiv19/nativescript-cfalert-dialog#38]
Hi,
I can't build\run project due to this error:

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. Could not GET 'https://dl.bintray.com/crowdfire/cfalertdialog/com/google/android/gms/play-services-base/maven-metadata.xml'. Received status code 403 from server: Forbidden

Any ideas?

**Comment by shiv19** [comment]
https://dl.bintray.com/crowdfire/cfalertdialog/com/crowdfire/cfalertdialog/cfalertdialog/maven-metadata.xml

This is what it is supposed to look like. This library doesn't have play-services-base in it 🤔 
not sure why you are getting that dependency error

**Comment by tylerablake** [comment]
@shiv19 will the library and plugin reference need to be updated? It sounds like bintray is going to be deprecated in favor of maven on May 1st.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by shiv19** [comment]
Hey @tylerablake, yes you're right, I found out about that just yesterday.
I'll add maven to the gradle file and do an update for this plugin soon.

**Comment by tylerablake** [comment]
Awesome, thanks @shiv19!

**Comment by nmandyam** [comment]
Hit the same issue. Sorry to sound pushy, but: Any idea when this will be fixed? Thanks for a terrific plugin!

**Comment by JacquesBeets** [comment]
Hi @shiv19 , have you been able to look into this issue or is there another way we could get this working as we urgently need to get an update up on the play store but this is causing our build process to fail?

**Comment by shiv19** [comment]
@JacquesBeets this has already been addressed in the latest release :)

**Comment by shiv19** [comment]
Fixed in version 1.0.16

**Comment by JacquesBeets** [comment]
@shiv19 Legend! :)
