### ISSUE TITLE
cancellable: false - does not work (Android)

### ISSUE THREAD

**Issue by venkateshsj** [shiv19/nativescript-cfalert-dialog#6]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?

`Android 8.0 - OnePlus3 (Oxygen OS 5.0.2)`

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

```
nativescript - 3.4.3 - Up to date
tns-core-modules - 3.4.1 - Up to date
tns-android - 3.4.2 - Up to date
tns-ios - 3.4.1 - Not installed
```

```
"dependencies": {
    "nativescript-animatecss": "1.0.0",
    "nativescript-appversion": "1.4.1",
    "nativescript-cardview": "2.0.5",
    "nativescript-cfalert-dialog": "1.0.6",
    "nativescript-checkbox": "3.0.3",
    "nativescript-dom": "2.0.0",
    "nativescript-exit": "1.0.1",
    "nativescript-fancyalert": "1.2.0",
    "nativescript-floatingactionbutton": "4.1.3",
    "nativescript-globalevents": "1.2.1",
    "nativescript-loading-indicator": "2.4.0",
    "nativescript-modal-datetimepicker": "1.1.0",
    "nativescript-pro-ui": "3.4.1",
    "nativescript-snackbar": "2.0.1",
    "nativescript-textinputlayout": "2.0.2",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toasts": "1.0.3",
    "nativescript-toolbox": "3.0.1",
    "nativescript-vibrate": "2.0.1",
    "tns-core-modules": "~3.4.0"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "~0.9.1",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Open the following file in your code folder,
`<code-folder-path>\node_modules\nativescript-cfalert-dialog\cfalert-dialog.android.js`

There is a statement at line no.84 to set whether dialog should be cancelable or not =>
`builder.setCancelable(options.cancellable);`

Reference Url -> https://developer.android.com/reference/android/app/AlertDialog.Builder.html#setCancelable(boolean)

I am assuming setting a value of 'false' to the parameter 'cancellable' should give the desired result of the dialog being non-dismissable. But the dialog still gets dismissed by tapping elsewhere on the screen or the device back button. Please guide what can be done to achieve the desired result.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with an application or refer to a repository with an application where the problem is reproducible.

**Comment by shiv19** [comment]
Fixing this now

**Comment by shiv19** [comment]
@venkateshsj Thanks for reporting this. And sorry for the delay.
Please update to v1.0.7
