### ISSUE TITLE
How to put edittext inside notificaion?

### ISSUE THREAD

**Issue by xellDart** [shiv19/nativescript-cfalert-dialog#7]

**Comment by shiv19** [comment]
create a edit text nativeView and pass it as the footer view to this plugin.

**Comment by mahavirvataliya** [comment]
```
var layout = new StackLayout();
// create dynamic content
var label = new Label();
label.text = "dynamic";
// connect to live view
layout.addChild(label)
textView.text = initialValue;
 let options: DialogOptions = {
  dialogStyle: CFAlertStyle.BOTTOM_SHEET,
  title:title,
  headerView: layout
 };

cfalertDialog.show(options);

```


gives error

like
**Error: Cannot convert object to Landroid/view/View; at index 0**

**Comment by shiv19** [comment]
@mahavirvataliya
The headerView takes in a nativeView as argument 

So you would want to do something like

const isAndroid = require("platform").isAndroid;

Or 

import { isAndroid } from "platform" 

`headerView: isAndroid ? layout.android : layout.ios`

**Comment by mahavirvataliya** [comment]
ok Thanks

**Comment by mahavirvataliya** [comment]
Sorry it is not showing in dialog

Error Removed But view not Show

**Comment by shiv19** [comment]
In that case, i recommend you read the plugin docs for the android library CFAlertDialog, they will have a sample implementation for the same.

Also try adding just the label, and not some layout like stack layout. 

Maybe it only takes widgets and not layouts. 
(i haven't tried that)

**Comment by mahavirvataliya** [comment]
```

			let stackLayout = new StackLayout();
			let label = new Label();
			label.text = "THis is Label";
			let image = new Image();
			image.src = "https://via.placeholder.com/200/dee9fc/000000/&text=MRV";

			stackLayout.addChild(image);
			stackLayout.addChild(label);

			let options: DialogOptions = {
				dialogStyle: CFAlertStyle.ALERT,
				title:title,
				cancellable: true,
				headerView:stackLayout.android
}
```

I have Try it not working

added label

**Comment by mahavirvataliya** [comment]
as i console logged the stackLayout.android gives undefined

**Comment by shiv19** [comment]
In that case it is best to create a native view
   ``` 
// IOS 
const nativeView = UILabel.new();
nativeView.text = "Native Button";
nativeView.frame = CGRectMake(0,0,50,50);
```
```
// Android 
const nativeView = new android.widget.TextView(context);
nativeView.setText("Native Button");
nativeView.setWidth(50);
nativeView.setHeight(50);
 ```

**Comment by mahavirvataliya** [comment]
Wow Thanks I am Also think of that as view should be initialized first so.
Is works

**Comment by shiv19** [comment]
Similarly you can create editText native view and use it with this plugin.

**Comment by farfromrefug** [comment]
@shiv19  as a reference you can put a nativescript view for footerView and headerView.
However the lib will force the view to be "MATCH_PARENT" on android. Which means if you want the view be 200px you need to have a subview of height 200px.

**Comment by shiv19** [comment]
@farfromrefug
I see, thanks for the information.
Have you tried doing
`nativescriptView.android.setHeight(200)`?

**Comment by farfromrefug** [comment]
setHeight only exists on TextView! plus i want to be cross-platform

**Comment by shiv19** [comment]
We can fork the android lib and fix that.

Currently what is the behavior on iOS? Does it force the view to "MATCH_PARENT" too?

**Comment by farfromrefug** [comment]
@shiv19 did not have to try it yet. But i don't think so from my experience with alertviewcontroller.
And i don't think you need to fork. Works well as it is

**Comment by shiv19** [comment]
@farfromrefug
Alright then. 
Thank you :)
